import localFont from "next/font/local";
import "./globals.css";

const montserrat = localFont({
	src: [
		{
			path: "../public/fonts/montserrat/Montserrat-Black.ttf",
			weight: "800",
			style: "normal",
		},
		{
			path: "../public/fonts/montserrat/Montserrat-Bold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "../public/fonts/montserrat/Montserrat-SemiBold.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/montserrat/Montserrat-Italic.ttf",
			weight: "400",
			style: "italic",
		},
		{
			path: "../public/fonts/montserrat/Montserrat-Regular.ttf",
			weight: "400",
			style: "normal",
		},
	],
	variable: "--font-montserrat",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={montserrat.variable}>{children}</body>
		</html>
	);
}
